backend/config/routes.rb
Rails.application.routes.draw do  
  scope :api, defaults: {format: :json} do
    resources :private_contents, :public_contents
    get '/current_user', to: 'current_user#index'
    devise_for :users, path: '', path_names: {
      sign_in: 'login',
      sign_out: 'logout',
      registration: 'signup'
    },
    controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations'
    }
  end
end

backend/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

backend/app/models/private_content.rb
class PrivateContent < ApplicationRecord
end

backend/app/models/public_content.rb
class PublicContent < ApplicationRecord
end

backend/app/models/user.rb
class User < ApplicationRecord
  include Devise::JWT::RevocationStrategies::JTIMatcher
  devise :database_authenticatable, :registerable, :validatable,
         :jwt_authenticatable, jwt_revocation_strategy: self
end

backend/app/controllers/application_controller.rb
class ApplicationController < ActionController::API
  include ActionController::MimeResponds
  respond_to :json
end

backend/app/controllers/current_user_controller.rb
class CurrentUserController < ApplicationController
  before_action :authenticate_user!
  def index
    render json: current_user, status: :ok
  end
end

backend/app/controllers/private_contents_controller.rb
class PrivateContentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_private_content, only: %i[ show update destroy ]

  # GET /private_contents
  def index
    @private_contents = PrivateContent.all

    render json: @private_contents
  end

  # GET /private_contents/1
  def show
    render json: @private_content
  end

  # POST /private_contents
  def create
    @private_content = PrivateContent.new(private_content_params)

    if @private_content.save
      render json: @private_content, status: :created, location: @private_content
    else
      render json: @private_content.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /private_contents/1
  def update
    if @private_content.update(private_content_params)
      render json: @private_content
    else
      render json: @private_content.errors, status: :unprocessable_entity
    end
  end

  # DELETE /private_contents/1
  def destroy
    @private_content.destroy
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_private_content
      @private_content = PrivateContent.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def private_content_params
      params.require(:private_content).permit(:name)
    end
end

backend/app/controllers/public_contents_controller.rb
class PublicContentsController < ApplicationController
  before_action :set_public_content, only: %i[ show edit update destroy ]

  # GET /public_contents or /public_contents.json
  def index
    @public_contents = PublicContent.all
  end

  # GET /public_contents/1 or /public_contents/1.json
  def show
  end

  # GET /public_contents/new
  def new
    @public_content = PublicContent.new
  end

  # GET /public_contents/1/edit
  def edit
  end

  # POST /public_contents or /public_contents.json
  def create
    @public_content = PublicContent.new(public_content_params)

    respond_to do |format|
      if @public_content.save
        format.html { redirect_to public_content_url(@public_content), notice: "Public content was successfully created." }
        format.json { render :show, status: :created, location: @public_content }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @public_content.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /public_contents/1 or /public_contents/1.json
  def update
    respond_to do |format|
      if @public_content.update(public_content_params)
        format.html { redirect_to public_content_url(@public_content), notice: "Public content was successfully updated." }
        format.json { render :show, status: :ok, location: @public_content }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @public_content.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /public_contents/1 or /public_contents/1.json
  def destroy
    @public_content.destroy

    respond_to do |format|
      format.html { redirect_to public_contents_url, notice: "Public content was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_public_content
      @public_content = PublicContent.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def public_content_params
      params.require(:public_content).permit(:name)
    end
end

backend/app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  respond_to :json
  private

  def respond_with(resource, _opts = {})
    if resource.persisted?
      render json: {
        status: {code: 200, message: 'Signed up sucessfully.'},
        data: UserSerializer.new(resource).serializable_hash[:data][:attributes]
      }
    else
      render json: {
        status: {message: "User couldn't be created successfully. #{resource.errors.full_messages.to_sentence}"}
      }, status: :unprocessable_entity
    end
  end
end

backend/app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  respond_to :json
  private

  def respond_with(resource, _opts = {})
    render json: {
      status: {code: 200, message: 'Logged in sucessfully.'},
      data: UserSerializer.new(resource).serializable_hash[:data][:attributes]
    }, status: :ok
  end

  def respond_to_on_destroy
    if current_user
      render json: {
        status: 200,
        message: "logged out successfully"
      }, status: :ok
    else
      render json: {
        status: 401,
        message: "Couldn't find an active session."
      }, status: :unauthorized
    end
  end
end

backend/app/helpers/application_helper.rb
module ApplicationHelper
end

backend/app/helpers/current_user_helper.rb
module CurrentUserHelper
end

backend/app/helpers/private_contents_helper.rb
module PrivateContentsHelper
end

backend/app/helpers/public_contents_helper.rb
module PublicContentsHelper
end

backend/app/views/current_user/index.html.erb
<h1>CurrentUser#index</h1>
<p>Find me in app/views/current_user/index.html.erb</p>

backend/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Backend</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

backend/app/views/private_contents/_form.html.erb
<%= form_with(model: private_content) do |form| %>
  <% if private_content.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(private_content.errors.count, "error") %> prohibited this private_content from being saved:</h2>

      <ul>
        <% private_content.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

backend/app/views/private_contents/_private_content.html.erb
<div id="<%= dom_id private_content %>">
  <p>
    <strong>Name:</strong>
    <%= private_content.name %>
  </p>

</div>

backend/app/views/private_contents/edit.html.erb
<h1>Editing private content</h1>

<%= render "form", private_content: @private_content %>

<br>

<div>
  <%= link_to "Show this private content", @private_content %> |
  <%= link_to "Back to private contents", private_contents_path %>
</div>

backend/app/views/private_contents/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Private contents</h1>

<div id="private_contents">
  <% @private_contents.each do |private_content| %>
    <%= render private_content %>
    <p>
      <%= link_to "Show this private content", private_content %>
    </p>
  <% end %>
</div>

<%= link_to "New private content", new_private_content_path %>

backend/app/views/private_contents/new.html.erb
<h1>New private content</h1>

<%= render "form", private_content: @private_content %>

<br>

<div>
  <%= link_to "Back to private contents", private_contents_path %>
</div>

backend/app/views/private_contents/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @private_content %>

<div>
  <%= link_to "Edit this private content", edit_private_content_path(@private_content) %> |
  <%= link_to "Back to private contents", private_contents_path %>

  <%= button_to "Destroy this private content", @private_content, method: :delete %>
</div>

backend/app/views/public_contents/_form.html.erb
<%= form_with(model: public_content) do |form| %>
  <% if public_content.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(public_content.errors.count, "error") %> prohibited this public_content from being saved:</h2>

      <ul>
        <% public_content.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

backend/app/views/public_contents/_public_content.html.erb
<div id="<%= dom_id public_content %>">
  <p>
    <strong>Name:</strong>
    <%= public_content.name %>
  </p>

</div>

backend/app/views/public_contents/edit.html.erb
<h1>Editing public content</h1>

<%= render "form", public_content: @public_content %>

<br>

<div>
  <%= link_to "Show this public content", @public_content %> |
  <%= link_to "Back to public contents", public_contents_path %>
</div>

backend/app/views/public_contents/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Public contents</h1>

<div id="public_contents">
  <% @public_contents.each do |public_content| %>
    <%= render public_content %>
    <p>
      <%= link_to "Show this public content", public_content %>
    </p>
  <% end %>
</div>

<%= link_to "New public content", new_public_content_path %>

backend/app/views/public_contents/new.html.erb
<h1>New public content</h1>

<%= render "form", public_content: @public_content %>

<br>

<div>
  <%= link_to "Back to public contents", public_contents_path %>
</div>

backend/app/views/public_contents/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @public_content %>

<div>
  <%= link_to "Edit this public content", edit_public_content_path(@public_content) %> |
  <%= link_to "Back to public contents", public_contents_path %>

  <%= button_to "Destroy this public content", @public_content, method: :delete %>
</div>